
const GENRE_MAP: Record<string, string> = {
  sf_history: 'Альтернативная история',
  sf_action: 'Боевая фантастика',
  sf_epic: 'Эпическая фантастика',
  sf_heroic: 'Героическая фантастика',
  sf_detective: 'Детективная фантастика',
  sf_cyberpunk: 'Киберпанк',
  sf_space: 'Космическая фантастика',
  sf_social: 'Социальная фантастика',
  sf_horror: 'Ужасы и мистика',
  sf_humor: 'Юмористическая фантастика',
  sf_fantasy: 'Фэнтези',
  sf: 'Научная фантастика',
  sf_stimpank: 'Стимпанк',
  sf_postapocalyptic: 'Постапокалипсис',
  sf_etc: 'Прочая фантастика',
  sf_litrpg: 'ЛитРПГ',
  det_classic: 'Классический детектив',
  det_police: 'Полицейский детектив',
  det_action: 'Боевик',
  det_irony: 'Иронический детектив',
  det_history: 'Исторический детектив',
  det_espionage: 'Шпионский детектив',
  det_crime: 'Криминальный детектив',
  det_political: 'Политический детектив',
  det_maniac: 'Маньяки',
  det_hard: 'Крутой детектив',
  detective: 'Детектив',
  det_su: 'Советский детектив',
  det_cozy: 'Уютный детектив',
  det: 'Детектив',
  prose_classic: 'Классическая проза',
  prose_history: 'Историческая проза',
  prose_contemporary: 'Современная проза',
  prose_counter: 'Контркультура',
  prose_rus_classic: 'Русская классическая проза',
  prose_su_classics: 'Советская классика',
  prose_military: 'Военная проза',
  prose: 'Проза',
  prose_abs: 'Абсурдистская проза',
  prose_magic: 'Магический реализм',
  love_contemporary: 'Современные любовные романы',
  love_history: 'Исторические любовные романы',
  love_detective: 'Остросюжетные любовные романы',
  love_short: 'Короткие любовные романы',
  love_erotica: 'Эротика',
  love_sf: 'Любовное фэнтези',
  love: 'Любовные романы',
  adv_western: 'Вестерн',
  adv_history: 'Исторические приключения',
  adv_indian: 'Приключения про индейцев',
  adv_maritime: 'Морские приключения',
  adv_geo: 'Путешествия и география',
  adv_animal: 'Природа и животные',
  adventure: 'Приключения',
  adv: 'Приключения',
  child_det: 'Детские детективы',
  child_prose: 'Детская проза',
  child_adv: 'Детские приключения',
  child_education: 'Детская образовательная',
  child_sf: 'Детская фантастика',
  child_tale: 'Сказки',
  child_verse: 'Детские стихи',
  children: 'Детская литература',
  poetry: 'Поэзия',
  dramaturgy: 'Драматургия',
  antique_ant: 'Античная литература',
  antique_european: 'Европейская старинная',
  antique_russian: 'Древнерусская',
  antique_east: 'Восточная литература',
  antique_myths: 'Мифы и легенды',
  antique: 'Старинная литература',
  sci_history: 'История',
  sci_psychology: 'Психология',
  sci_culture: 'Культурология',
  sci_religion: 'Религиоведение',
  sci_philosophy: 'Философия',
  sci_politics: 'Политика',
  sci_business: 'Бизнес',
  sci_juris: 'Юриспруденция',
  sci_linguistic: 'Языкознание',
  sci_medicine: 'Медицина',
  sci_phys: 'Физика',
  sci_math: 'Математика',
  sci_chem: 'Химия',
  sci_biology: 'Биология',
  sci_tech: 'Технические науки',
  sci_ecology: 'Экология',
  sci_geo: 'Геология',
  science: 'Наука',
  sci_economy: 'Экономика',
  sci_pedagogy: 'Педагогика',
  sci_cosmos: 'Астрономия',
  sci_philology: 'Филология',
  sci_social_studies: 'Обществознание',
  sci_state: 'Госуправление',
  sci_veterinary: 'Ветеринария',
  sci_popular: 'Научпоп',
  sci: 'Наука',
  comp_db: 'Базы данных',
  comp_hard: 'Компьютерное железо',
  comp_osnet: 'ОС и сети',
  comp_programming: 'Программирование',
  comp_soft: 'Программы',
  comp_www: 'Интернет',
  computers: 'Компьютеры',
  comp: 'Компьютеры',
  ref_encyc: 'Энциклопедии',
  ref_dict: 'Словари',
  ref_ref: 'Справочники',
  reference: 'Справочная литература',
  ref_guide: 'Руководства',
  ref: 'Справочники',
  nonf_biography: 'Биографии',
  nonf_publicism: 'Публицистика',
  nonf_criticism: 'Критика',
  nonfiction: 'Документальная литература',
  design: 'Искусство и дизайн',
  geo_guides: 'Путеводители',
  nonf_military: 'Военное дело',
  nonf: 'Документальное',
  religion_rel: 'Религия',
  religion_esoterics: 'Эзотерика',
  religion_self: 'Самосовершенствование',
  religion: 'Религия',
  religion_budda: 'Буддизм',
  religion_christianity: 'Христианство',
  religion_islam: 'Ислам',
  religion_paganism: 'Язычество',
  religion_judaism: 'Иудаизм',
  religion_hinduism: 'Индуизм',
  religion_orthodoxy: 'Православие',
  religion_catholicism: 'Католицизм',
  humor_prose: 'Юмористическая проза',
  humor_verse: 'Юмористические стихи',
  humor_anecdote: 'Анекдоты',
  humor: 'Юмор',
  humor_satire: 'Сатира',
  home_cooking: 'Кулинария',
  home_pets: 'Домашние животные',
  home_crafts: 'Хобби и ремёсла',
  home_entertain: 'Развлечения',
  home_health: 'Здоровье',
  home_garden: 'Сад и огород',
  home_diy: 'Сделай сам',
  home_sport: 'Спорт',
  home_sex: 'Эротика, секс',
  home: 'Дом и семья',
  other: 'Прочее',
  periodic: 'Периодика',
  job_interview: 'Интервью',
  music: 'Музыка',
  cine: 'Кино',
  fanfiction: 'Фанфик',
  unrecognised: 'Неопознанное',
}

export function getGenreName(code: string): string {
  return GENRE_MAP[code] || code
}

export function getAllGenres(): Record<string, string> {
  return { ...GENRE_MAP }
}
